### ISSUE TITLE
npm package missing

### ISSUE THREAD

**Issue by mindyourlifeguide** [StatelyCloud/connect-devtools#1]
An error occurred when trying to install, checked on the npm website - indeed, there is no such package.

I copied it locally for now, but I would like to give you credit and install it through your package.

Thank you for your work!

**Comment by bhollis** [comment]
Ah, good catch - we'd expected that we would move this over to the connectrpc org by now, but haven't heard anything from them. I'll get the package published.

**Comment by bhollis** [comment]
This is now published at https://www.npmjs.com/package/connect-devtools

**Comment by mindyourlifeguide** [comment]
Thanks!
I also created an [issue](https://github.com/connectrpc/connect-es/issues/1365) in connectrpc - I'll wait for their response.

Cheers!
